#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "wallabag2"
name = "Wallabag"
description.en = "A self hostable read-it-later app"
description.fr = "Une application de lecture-plus-tard auto-hébergeable"

version = "2.5.4~ynh2"

maintainers = ["Lapineige"]

[upstream]
license = "MIT"
website = "https://www.wallabag.org"
demo = "https://demo.yunohost.org/wallabag/"
admindoc = "https://doc.wallabag.org/en/"
code = "https://github.com/wallabag/wallabag"
cpe = "cpe:2.3:a:wallabag:wallabag"
fund = "???" # FIXME: optional but recommended (or remove if irrelevant / not applicable). This is meant to be an URL where people can financially support this app, especially when its development is based on volunteers and/or financed by its community. YunoHost may later advertise it in the webadmin.

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = true
sso = false
disk = "50M" # FIXME: replace with an **estimate** minimum disk requirement. e.g. 20M, 400M, 1G, ...
ram.build = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...
ram.runtime = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/wallabag"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

[resources]
    [resources.sources.main]
    url = "https://github.com/wallabag/wallabag/releases/download/2.5.4/wallabag-2.5.4.tar.gz"
    sha256 = "c953105e3181f18bf592541a1c46c318c6663ad00d4687052676b02a7d74c618"

    autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "php7.4-cli",
        "php7.4-mysql",
        "php7.4-json",
        "php7.4-gd",
        "php7.4-tidy",
        "php7.4-curl",
        "php7.4-gettext",
        "php7.4-redis",
        "php7.4-xml",
        "php7.4-mbstring",
        "php7.4-ldap",
        "php7.4-intl",
        "mariadb-server",
    ]

    [resources.database]
    type = "mysql"
